name: Jekyll site CI

         <p>
            <a href="ms-windows-store://pdp/?productid=9PFPC2WNCM7C">RetroArcade Village</a>
         </p>
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspaces }}:/srv/jekyll -v ${{ github.workspaces }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

